import { ServiceType, ServiceContent, Subcontractor, Lead, JobStatus } from './types';

export const MOCK_SUBCONTRACTORS: Subcontractor[] = [
  { id: 'sub-1', name: 'CleanTeam Alpha', rating: 4.8, specialties: [ServiceType.HouseCleaning, ServiceType.DeepCleaning], available: true },
  { id: 'sub-2', name: 'Sparkle Pros LLC', rating: 4.9, specialties: [ServiceType.Office], available: true },
  { id: 'sub-3', name: 'MoveReady Maids', rating: 4.7, specialties: [ServiceType.MoveOut], available: false },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'job-101',
    customerName: 'Alice Johnson',
    email: 'alice@example.com',
    address: '123 Maple Ave, Westchester, NY',
    zipCode: '10583',
    serviceType: ServiceType.DeepCleaning,
    date: '2023-11-15',
    frequency: 'One-time',
    status: JobStatus.New,
    quoteAmount: 350,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'job-102',
    customerName: 'TechStart Office',
    email: 'manager@techstart.io',
    address: '400 Enterprise Blvd, White Plains, NY',
    zipCode: '10601',
    serviceType: ServiceType.Office,
    date: '2023-11-16',
    frequency: 'Weekly',
    status: JobStatus.Booked,
    assignedTo: 'sub-2',
    quoteAmount: 200,
    createdAt: new Date().toISOString(),
  },
];

export const SERVICE_CONTENT: Record<string, ServiceContent> = {
  'house-cleaning': {
    slug: 'house-cleaning',
    title: 'Standard House Cleaning',
    shortDesc: 'Regular cleaning to keep your home fresh and tidy.',
    longDesc: 'Our standard house cleaning service is perfect for maintaining a tidy home on a weekly, bi-weekly, or monthly basis. We focus on high-traffic areas, dusting, vacuuming, mopping, and sanitizing bathrooms and kitchens. Relax and enjoy your free time while our professional subcontractors make your home shine.',
    imagePlaceholder: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=1200',
    benefits: ['Consistent scheduling', 'Eco-friendly products available', 'Insured and vetted cleaners', '100% Satisfaction Guarantee'],
    faqs: [
      { question: 'How do you vet your cleaners?', answer: 'Every cleaner in the ClearVista network undergoes a rigorous screening process including a nationwide criminal background check, reference checks, and a detailed practical skills assessment.' },
      { question: 'Do I need to provide cleaning supplies?', answer: 'Our professionals arrive fully equipped with high-quality cleaning supplies and commercial-grade vacuums. If you have specific products you prefer we use for certain surfaces, just let us know!' },
      { question: 'What is your cancellation policy?', answer: 'We understand plans change. You can cancel or reschedule up to 24 hours before your appointment without penalty. Cancellations within 24 hours may incur a small convenience fee.' },
      { question: 'Do I need to be home?', answer: 'No, most of our clients provide a key or door code. Our secure key management protocol ensures your home remains safe and private.' },
      { question: 'Are you insured and bonded?', answer: 'Absolutely. ClearVista is fully insured and bonded. We carry comprehensive liability and property damage coverage for your total peace of mind.' },
      { question: 'Are your products pet and child safe?', answer: 'Yes, we prioritize non-toxic, eco-friendly cleaning solutions that are powerful against dirt but safe for your family and furry friends.' },
    ],
    seoTitle: 'Westchester House Cleaning Services | ClearVista Maids',
    seoDescription: 'Reliable house cleaning in Westchester, NY. Serving White Plains, Scarsdale, and surrounding areas. Book your weekly or bi-weekly maid service today with ClearVista.',
    seoKeywords: 'house cleaning westchester ny, maid service white plains, home cleaning scarsdale, professional house cleaners',
    pricingExamples: [
      { label: 'Studio / 1 Bath', price: '$120 - $150' },
      { label: '1 Bed / 1 Bath', price: '$135 - $170' },
      { label: '2 Bed / 1 Bath', price: '$165 - $210' },
      { label: '2 Bed / 2 Bath', price: '$180 - $240' },
      { label: '3 Bed / 2 Bath', price: '$230 - $300' },
      { label: '4 Bed / 3 Bath', price: '$280 - $380' },
      { label: '5+ Bed', price: '$350 - $450+' },
    ],
  },
  'deep-cleaning': {
    slug: 'deep-cleaning',
    title: 'Deep Cleaning Services',
    shortDesc: 'A thorough top-to-bottom clean for homes that need extra attention.',
    longDesc: 'Our deep cleaning service goes beyond the surface. We tackle built-up grime, dust baseboards, clean behind appliances, and scrub tile grout. This is highly recommended for first-time customers or homes that haven\'t been professionally cleaned in over 3 months.',
    imagePlaceholder: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=1200',
    benefits: ['Eliminates hidden allergens', 'Restores appliance shine', 'Detailed attention to nooks and crannies', 'Prepares home for regular maintenance'],
    faqs: [
      { question: 'What is the difference between standard and deep cleaning?', answer: 'A deep clean includes detailed tasks like scrubbing baseboards, cleaning inside cabinets, deep-cleaning grout, and tackling heavy soap scum or grease build-up that isn\'t covered in a routine maintenance clean.' },
      { question: 'How often should I get a deep clean?', answer: 'We typically recommend a deep clean every 3-6 months, or as a "reset" before starting a recurring weekly or bi-weekly standard service.' },
      { question: 'Do you clean behind large appliances?', answer: 'If appliances like the refrigerator or stove can be safely pulled out without damaging the floor, our cleaners will clean behind and underneath them.' },
      { question: 'How long does a deep clean take?', answer: 'Due to the level of detail, deep cleans usually take 50-100% longer than a standard clean. A typical 3-bedroom home takes between 5-8 labor hours.' },
      { question: 'Should I tidy up before you arrive?', answer: 'While not required, "decluttering" surfaces helps our cleaners focus their time on deep-cleaning and sanitizing rather than organizing personal items.' },
    ],
    seoTitle: 'Best Deep Cleaning Services White Plains NY | ClearVista Cleaning',
    seoDescription: 'Thorough deep cleaning services for homes in Westchester County. We scrub, sanitize, and detail clean every corner. Perfect for spring cleaning by ClearVista.',
    seoKeywords: 'deep cleaning westchester ny, deep house cleaning white plains, spring cleaning services ny, detailed home cleaning',
    pricingExamples: [
      { label: 'Studio / 1 Bath', price: '$170 - $220' },
      { label: '1 Bed / 1 Bath', price: '$190 - $250' },
      { label: '2 Bed / 1 Bath', price: '$230 - $300' },
      { label: '2 Bed / 2 Bath', price: '$260 - $340' },
      { label: '3 Bed / 2 Bath', price: '$310 - $420' },
      { label: '4 Bed / 3 Bath', price: '$380 - $520' },
      { label: '5+ Bed', price: '$450 - $650+' },
    ],
  },
  'move-out': {
    slug: 'move-out',
    title: 'Move-In / Move-Out Cleaning',
    shortDesc: 'Ensure your security deposit return or start fresh in a new home.',
    longDesc: 'Moving is stressful enough without worrying about the cleaning. Our Move-In/Move-Out service is a comprehensive clean designed to meet landlord and property management standards. We ensure the property is completely empty of dust and debris.',
    imagePlaceholder: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&q=80&w=1200',
    benefits: ['Deposit back guarantee support', 'Covers inside cabinets and drawers', 'Flexible timing for moving day', 'Checklist based on realtor standards'],
    faqs: [
      { question: 'Does the home need to be empty?', answer: 'Yes. For the most efficient and thorough move-out clean, the home should be completely empty of furniture and personal belongings.' },
      { question: 'Do you guarantee my security deposit return?', answer: 'While we cannot control your landlord\'s decisions, we use a comprehensive Move-Out Checklist that covers all standard requirements to ensure the property is in "move-in ready" condition.' },
      { question: 'Do I need to keep the utilities on?', answer: 'Yes. For a successful clean, we require active electricity and hot water to power our equipment and effectively sanitize surfaces.' },
      { question: 'Is cleaning inside cabinets and drawers included?', answer: 'Absolutely. Unlike a standard clean, the move-in/out service specifically includes wiping out the interior of all kitchen and bathroom cabinets and drawers.' },
      { question: 'Do you clean the walls?', answer: 'We perform a general dusting of walls and spot-cleaning of scuffs. Full-wall washing is available as a custom add-on for homes with heavy smoking or pet history.' },
    ],
    seoTitle: 'Move-Out & Move-In Cleaning Westchester NY | ClearVista Deposit Support',
    seoDescription: 'Professional move-out cleaning in Westchester, NY. Ensure you get your security deposit back with our checklist-based cleaning for tenants and landlords with ClearVista.',
    seoKeywords: 'move out cleaning westchester, move in cleaning white plains, apartment turnover cleaning, rental cleaning services',
    pricingExamples: [
      { label: 'Studio / 1 Bath', price: '$200 - $260' },
      { label: '1 Bed / 1 Bath', price: '$230 - $300' },
      { label: '2 Bed / 1 Bath', price: '$270 - $350' },
      { label: '2 Bed / 2 Bath', price: '$310 - $420' },
      { label: '3 Bed / 2 Bath', price: '$380 - $520' },
      { label: '4 Bed / 3 Bath', price: '$460 - $650' },
      { label: '5+ Bed', price: '$550 - $800+' },
    ],
  },
  'office-cleaning': {
    slug: 'office-cleaning',
    title: 'Commercial & Office Cleaning',
    shortDesc: 'Professional cleaning solutions for businesses and workspaces.',
    longDesc: 'A clean office is a productive office. We provide reliable commercial cleaning services for offices, retail spaces, and common areas. From emptying trash bins to sanitizing restrooms and breakrooms, we create a healthy environment for your employees and clients.',
    imagePlaceholder: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1200',
    benefits: ['After-hours availability', 'Customizable scopes of work', 'Supply restocking options', 'Professional appearance'],
    faqs: [
      { question: 'Can you clean after business hours?', answer: 'Yes. We offer flexible scheduling, including evenings and weekends, so our team can clean your office without disrupting your business operations.' },
      { question: 'Do you provide a Certificate of Insurance (COI)?', answer: 'Absolutely. We can provide a standard COI naming your business or property management company as additionally insured upon request.' },
      { question: 'What frequencies do you offer?', answer: 'We offer daily, weekly, bi-weekly, and monthly recurring schedules, as well as one-time deep cleans or post-event cleanups.' },
      { question: 'Can you help with supply restocking?', answer: 'Yes, we can manage the inventory and restocking of restroom and breakroom essentials like paper towels, soap, and trash liners as an added service.' },
      { question: 'Do you clean medical or high-tech spaces?', answer: 'Yes, our professionals are trained in high-touchpoint sanitization and proper protocol for professional office environments, including medical suites and tech hubs.' },
    ],
    seoTitle: 'Office Cleaning Services Westchester County | ClearVista Commercial',
    seoDescription: 'Trusted office cleaning and janitorial services in Westchester, NY. Customized cleaning plans for businesses in White Plains, Yonkers, and New Rochelle with ClearVista.',
    seoKeywords: 'office cleaning westchester ny, commercial cleaning white plains, janitorial services westchester, corporate office cleaners',
    pricingExamples: [
      { label: 'Small Office (up to 1,000 sq ft)', price: '$120 – $180 / visit' },
      { label: 'Medium Office (1,000 – 2,500 sq ft)', price: '$180 – $300 / visit' },
      { label: 'Large Office (2,500 – 5,000 sq ft)', price: '$300 – $550 / visit' },
      { label: '5,000+ sq ft', price: 'Custom Quote' },
    ],
  },
  'apartment-cleaning': {
    slug: 'apartment-cleaning',
    title: 'Apartment & Condo Cleaning',
    shortDesc: 'Specialized cleaning for high-rise living and urban spaces.',
    longDesc: 'Our Apartment & Condo cleaning service is specifically tailored for residents of multi-family buildings and urban high-rises. We understand the logistical challenges of apartment living, from navigating building security to optimizing smaller footprints. We focus on maximizing space, sanitizing high-touch surfaces, and ensuring your city home is a true sanctuary.',
    imagePlaceholder: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1200',
    benefits: ['Building protocol compliant', 'Balcony & window track detailing', 'Pet-friendly solutions', 'Flexible time slots for commuters'],
    faqs: [
      { question: 'Do you coordinate with building management?', answer: 'Yes, we are experienced in working with building concierges and management companies for key access and insurance certificate (COI) requirements.' },
      { question: 'Do you clean balconies?', answer: 'Balcony cleaning can be added to your service for a small additional fee, ensuring your outdoor space is just as clean as your indoor space.' },
      { question: 'What about parking?', answer: 'We ask that you let us know of any specific parking instructions or loading zones to ensure our teams arrive on time.' },
      { question: 'Can you clean studio apartments?', answer: 'Absolutely. We have specialized pricing for studios and one-bedroom apartments that provides a thorough clean at an efficient price point.' },
    ],
    seoTitle: 'Apartment Cleaning Westchester NY | Condo Maid Services | ClearVista',
    seoDescription: 'Professional apartment and condo cleaning services in Westchester County. Expert maids for downtown rentals and luxury high-rises. Vetted and insured.',
    seoKeywords: 'apartment cleaning westchester, condo cleaning white plains, urban maid service ny, luxury apartment cleaners',
    pricingExamples: [
      { label: 'Studio / 1 Bath', price: '$110 – $150' },
      { label: '1 Bed / 1 Bath', price: '$130 – $170' },
      { label: '2 Bed / 1 Bath', price: '$150 – $200' },
      { label: '2 Bed / 2 Bath', price: '$170 – $230' },
      { label: '3 Bed / 2 Bath', price: '$210 – $280' },
      { label: '3 Bed / 3 Bath', price: '$240 – $320' },
      { label: '4+ Bed', price: '$300 – $400+' },
    ],
  },
};